## COLORSCHEME: tomorrow-min
set-option -g status "on"

# default statusbar colors
set-option -g status-bg "#1e1f21"
set-option -g status-fg "#c5c8c6"

# default window title colors
set-window-option -g window-status-style fg="#f0c674",bg="#1e1f21"
set-window-option -g window-status-activity-style fg="#81a2be",bg="#1e1f21"

# active window title colors
set-window-option -g window-status-current-style fg="#1e1f21",bg=default

# pane border
set-option -g display-panes-active-colour "#c5c8c6"
set-option -g display-panes-colour "#1e1f21"

# message infos
set-option -g message-style fg="#c5c8c6",bg="#282a2e"

# writting commands inactive
set-option -g message-command-style fg="#c5c8c6",bg="#282a2e"

# pane number display
set-option -g display-panes-active-colour "#e0e0e0"
set-option -g display-panes-colour "#1e1f21"

# clock
set-window-option -g clock-mode-colour "#81a2be"

# bell
set-window-option -g window-status-bell-style fg="#1e1f21",bg="#ff5b69"

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
# set-option -g status-style none
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-activity-style none
set-window-option -g window-status-style none
set-window-option -g window-status-separator ""

set-option -g status-left "#[fg=#c5c8c6, bg=#373b41] #S #[fg=#373b41, bg=#1e1f21, nobold, noitalics, nounderscore]"
set-option -g status-right "#[fg=#282a2e, bg=#1e1f21, nobold, nounderscore, noitalics]#[fg=#63666e,bg=#282a2e] %Y-%m-%d ⎸%H:%M #[fg=#c5c8c6, bg=#282a2e, nobold, noitalics, nounderscore]#[fg=#1e1f21, bg=#c5c8c6] #h "

set-window-option -g window-status-current-format "#[fg=#282a2e, bg=#c5c8c6, :nobold, noitalics, nounderscore]#[fg=#282a2e, bg=#f0c674] #I ⎸#[fg=#282a2e, bg=#f0c674, bold]#W #[fg=#f0c674, bg=#1e1f21, nobold, noitalics, nounderscore]"
set-window-option -g window-status-format "#[fg=#1e1f21,bg=#282a2e,noitalics]#[fg=#c5c8c6,bg=#282a2e] #I ⎸#[fg=#c5c8c6, bg=#282a2e]#W #[fg=#282a2e, bg=#1e1f21, noitalics]"

set -g default-terminal "alacritty"
set-option -ga terminal-overrides ",*:Tc:smso=^[[3m:smcup@:rmcup@"

# send the prefix to client inside window
bind-key -n C-a send-prefix

set -s escape-time 0

bind r source-file ~/.config/tmux.conf

# Vim style pane selection
bind C-h select-pane -L
bind C-j select-pane -D 
bind C-k select-pane -U
bind C-l select-pane -R

bind h split-window -h
bind v split-window -v

bind-key Down resize-pane -D 5
bind-key Up resize-pane -U 5
bind-key Left resize-pane -L 5
bind-key Right resize-pane -R 5

set-option -g default-shell /bin/zsh
