[bell]
animation = "Ease"
color = "0xebdbb2"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '0x1F1F1F'
foreground = '0xE0E0E0'

[colors.cursor]
text = '0x1F1F1F'
cursor = '0xE0E0E0'

[colors.normal]
black   = '0x1F1F1F'
red     = '0xCC6666'
green   = '0xB5BD68'
yellow  = '0xF0C674'
blue    = '0x81A2BE'
magenta = '0xB294BB'
cyan    = '0xCC6666'
white   = '0xE0E0E0'

[colors.bright]
black   = '0x727272'
red     = '0xCC6666'
green   = '0xB5BD68'
yellow  = '0xF0C674'
blue    = '0x81A2BE'
magenta = '0xB294BB'
cyan    = '0xCC6666'
white   = '0xE0E0E0'

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
#size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "InconsolataGo Nerd Font"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
# multiplier = 8

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
