
[bell]
animation = "Ease"
color = "0xebdbb2"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x665c54"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xfbf1c7"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "0xfbf1c7"
text = "0x282828"

[colors.normal]
black = "0x282828"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xfbf1c7"
yellow = "0xfabd2f"

[colors.primary]
background = "0x282828"
foreground = "0xfbf1c7"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 13

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "InputMono Nerd Font"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
# multiplier = 8

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
