[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-numix-blue
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-numix-blue
GtkTheme=oomox-numix-blue
IconTheme=oomox-numix-blue
MetacityTheme=oomox-numix-blue
